include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

# 右键 -> Reformat Code with 'dart format' 保存逗号
# https://pub-web.flutter-io.cn/packages/dart_style/changelog
formatter:
  trailing_commas: preserve
  page_width: 160