name: flutter_rapid_development_kit
description: Flutter Rapid Development Kit
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Provides internationalization and localization facilities, including message translation, plurals and genders, date/number formatting and parsing, and bidirectional text.
  # 提供国际化和本地化功能，包括消息翻译、复数和性别、日期/数字格式化和解析，以及双向文本。
  # https://pub.flutter-io.cn/packages/intl
  intl: 0.18.0

  # A flutter library to show images from the internet and keep them in the cache directory.
  # Flutter库，用于显示从互联网上获取的图像，并将它们保留在缓存目录中。
  # https://pub.flutter-io.cn/packages/cached_network_image/install
  cached_network_image: 3.2.3

  # A carousel slider widget.
  # 一个可滑动的组件，常用于图片轮播。
  # https://pub.flutter-io.cn/packages/carousel_slider
  carousel_slider: 4.2.1

  # OneContext provides a simple way to deal with Dialogs, Overlays, Navigations, Theme* and MediaQuery* with no need of BuildContext.
  # OneContext 提供了一种简单的方式来处理对话框、覆盖层、导航、主题和 MediaQuery，而无需使用 BuildContext。
  # https://pub.flutter-io.cn/packages/one_context
  # https://segmentfault.com/a/1190000023213991
#  one_context: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
